// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKdv1gstwGZaR51ZeW-IOgFNJV8ufVCvo',
    appId: '1:516153415128:android:52be65201d3e1052518ead',
    messagingSenderId: '516153415128',
    projectId: 'engaz-app-2',
    storageBucket: 'engaz-app-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnR04lm2v0QlSymFkl5k3xn_glijDJUw',
    appId: '1:516153415128:ios:85d58b6b0ec019d6518ead',
    messagingSenderId: '516153415128',
    projectId: 'engaz-app-2',
    storageBucket: 'engaz-app-2.firebasestorage.app',
    androidClientId: '516153415128-nb1pq6ihh6b0tti500p85noh1rqtbdmf.apps.googleusercontent.com',
    iosClientId: '516153415128-9dq1a1id5ad4hngoviddg4m4amk8tnup.apps.googleusercontent.com',
    iosBundleId: 'com.example.engazApp',
  );
}
